version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "y"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gdi9q2z1og7b"
s3_prefix = "y"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
